version = 1

[[annotations]]
path = ["**/*.json", "**/*.png", "**/*.ico", "**/*.webmanifest", "**/*.md", ".gitignore", ".gitattributes", ".prettierignore", ".prettierrc.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "© 2026 AP3X Records"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["public/musique/**"]
precedence = "override"
SPDX-FileCopyrightText = "© 2026 AP3X Records"
SPDX-License-Identifier = "CC-BY-NC-ND-4.0"
